export { default as Home } from './index/index'
export { default as Games } from './list/list'
export { default as SignIn } from './auth/signin'
export { default as SignUp } from './auth/signup'
export { default as PageNotFound } from './404/404error'
